# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e4b14d340cfd0fdfc7fec4b67f35b529ad387571a2733eef20d53361f8ce7bfb26de89594ad320000c3865b6781e66168d9d525fc1dd3a406391a84b61b9cbe7

test:
  secret_key_base: ba4dbc01c072e08b9dbb43f62548f9e4fe4ea7d3ec5865103384ff438ad3857c2d828efdc2d076d5066df6f5e019423baed1e2d035a34630ae48ec605cc3e2d7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
